# Interface Style
timeline_style=bar
timeline_size=20
timeline_persistency=
timeline_border=0
timeline_cache=true
controls_size=36
controls_persistency=
controls_margin=8
autohide=yes
window_border_size=0
top_bar_size=40
top_bar_persistency=playback

# Controls Layout (with icons)
controls=menu,open-file,prev,play-pause,next,subtitles,audio,space,shuffle,loop-playlist,fullscreen
